version: '3'
services:
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    network_mode:
      - "host"
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    network_mode: 
      - "host"        
  web:
    build:
      context: frontend
      dockerfile: Dockerfile 
    ports:
      - "4200:4200"
    network_mode:
      - "host"


