version: '3'
services:
   db:
     image: postgres
     volumes:
       - ./tmp/db:/var/lib/postgresql/data
     network_mode:
       "host"
   app:
     build:
       context: backend
       dockerfile: Dockerfile
     ports:
       - "9085:9085"
     network_mode: 
       "host"        
   web:
     build:
       context: frontend
       dockerfile: Dockerfile 
     ports:
       - "4200:4200"
     network_mode:
       "host"


