version: '3'
services:
   db:
     image: postgres
     volumes:
       - ./tmp/db:/var/lib/postgresql/data
   app:
     build:
       context: .
       dockerfile: Dockerfile.build
     environment:
       VERSION: dev
     volumes: 
       - "$HOME/.m2:/root/.m2"
     ports:
       - "8080:8080"
     command: mvn spring-boot:run    




