version: '3'
services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    network_mode: 
      "host"        
  web:
    build:
      context: frontend
      dockerfile: Dockerfile 
    ports:
      - "4200:4200"
    depends_on:
      - "app"    
    network_mode:
      "host"


