version: '3'
services:
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: queapp
      POSTGRES_PASSWORD: queapp
      POSTGRES_DB: queapp
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5432:5432"
    network_mode:
      "host"
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    network_mode: 
      "host"        
  web:
    build:
      context: frontend
      dockerfile: Dockerfile 
    ports:
      - "4200:4200"
    network_mode:
      "host"


