spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/queapp
    username: queapp
    password: queapp
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 9095