spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/queapp
    username: queapp
    password: queapp
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  endpoints:
    cors:
      allow-credentials: true
      allowed-origins: '*'
      allowed-methods: '*'
      allowed-headers: '*'
server:
  port: 9095